apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  namespace: default # Or your target namespace
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
      annotations:
        rollout-timestamp: "2025-08-26T00:00:00Z"
    spec:
      containers:
        - name: auth-service
          image: medhadji/auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: auth-uploads
              mountPath: /usr/src/app/uploads
          envFrom:
            - secretRef:
                name: auth-secrets
            - secretRef:
                name: mongo-secret
          env:
            - name: PORT
              value: "5000"
            - name: COMPANY_SERVICE_URL
              value: "http://company-service:5001"
      volumes:
        - name: auth-uploads
          persistentVolumeClaim:
            claimName: auth-service-uploads-pvc