apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: default
  labels:
    app: booking-service
spec:
  selector:
    app: booking-service
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
  type: ClusterIP
