apiVersion: v1
kind: Service
metadata:
  name: company-service
  namespace: default
  labels:
    app: company-service
spec:
  selector:
    app: company-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
