apiVersion: v1
kind: Secret
metadata:
  name: company-secrets
  namespace: default
stringData:
  JWT_SECRET: "7d2260dd33822b6d8c53b068ded2719aa13cfdd279ff0f114da3c4b063e61708"
  MONGODB_URI: "mongodb://adminuser:password123@mongodb-service:27017/sportify_companies?authSource=admin"
  MONGO_URI: "mongodb://adminuser:password123@mongodb-service:27017/sportify_companies?authSource=admin"
  # Optional external API keys
  CLOUDINARY_CLOUD_NAME: ""
  CLOUDINARY_API_KEY: ""
  CLOUDINARY_API_SECRET: ""
