apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: court-service-uploads-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: hostpath
