apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  labels:
    app: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi # Request 1GB of storage
  # storageClassName: standard # Uncomment and specify your storage class if needed, otherwise default will be used