apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW51c2Vy # adminuser
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQxMjM= # password123
  MONGO_URI: bW9uZ29kYjovL21vbmdvZGItc2VydmljZToyNzAxNy9hdXRoX2Ri # mongodb://mongodb-service:27017/auth_db