apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: default # Or your target namespace
type: Opaque
data:
  # echo -n 'root' | base64
  mongo-root-username: cm9vdA==
  # echo -n 'password123' | base64
  mongo-root-password: cGFzc3dvcmQxMjM=