apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway-service
  namespace: default # Or your target namespace
  labels:
    app: nginx-gateway
spec:
  selector:
    app: nginx-gateway # This must match the labels of your Nginx gateway pods
  ports:
  - protocol: TCP
    port: 80 # Port exposed externally
    targetPort: 80 # Port on the Nginx gateway pods
    nodePort: 30081 # NodePort on the host (30000-32767). Use this to reach the gateway from your host.
  type: NodePort # Expose on each Node's IP at a static port for local clusters