apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: default
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: medhadji/payment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5010
          envFrom:
            - secretRef:
                name: payment-secrets
          env:
            - name: PORT
              value: "5010"
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: MONGODB_URI
          livenessProbe:
            httpGet:
              path: /health
              port: 5010
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5010
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 5010
      targetPort: 5010
  type: ClusterIP