apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
  namespace: default
stringData:
  JWT_SECRET: "7d2260dd33822b6d8c53b068ded2719aa13cfdd279ff0f114da3c4b063e61708"
  MONGODB_URI: "mongodb://adminuser:password123@mongodb-service:27017/Sportify_payment?authSource=admin"
  MONGO_URI: "mongodb://adminuser:password123@mongodb-service:27017/Sportify_payment?authSource=admin"
  
  # Stripe Configuration - Real Stripe test keys
  # Get these from: https://dashboard.stripe.com/test/apikeys
  STRIPE_SECRET_KEY: "sk_test_51SAFgULHGqt3uW4qt6UfPtze7lldFA4e7aUdxtimYYnFQUndhJktk84xnL90v3WGPiZ9hQcrwa3GO1DtR2GdpkqJ00TP8E5Fex"
  STRIPE_PUBLISHABLE_KEY: "pk_test_51SAFgULHGqt3uW4q8Y4ZXiOMlAO2JPscx8nBUCu5tzD5d6rDYEhTfwfJ8WmuMeA0R5T6CeWwDqJRroDINEwRRWco00sTkfbR0F"
  # Webhook secret from: https://dashboard.stripe.com/test/webhooks (will be generated when we create the webhook)
  STRIPE_WEBHOOK_SECRET: "whsec_test_your_webhook_secret_here"
  
  # Frontend base URL for webhooks and redirects
  FRONTEND_BASE_URL: "http://localhost:3000"
  
  # PayPal Configuration (for future implementation)
  PAYPAL_CLIENT_ID: "your_paypal_client_id_here"
  PAYPAL_CLIENT_SECRET: "your_paypal_client_secret_here"
  PAYPAL_WEBHOOK_ID: "your_paypal_webhook_id_here"
  
  # Service URLs
  AUTH_SERVICE_URL: "http://auth-service:5000"
  BOOKING_SERVICE_URL: "http://booking-service:5005"
  COMPANY_SERVICE_URL: "http://company-service:5001"
  
  # Payment Configuration
  DEFAULT_CURRENCY: "USD"
  PAYMENT_DEADLINE_HOURS: "12"
  MAX_REFUND_DAYS: "30"
  AUTO_CHARGE_ENABLED: "true"
  AUTO_CANCEL_ENABLED: "true"
  
  # Email Configuration
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "mohamedhadji603@gmail.com"
  SMTP_PASS: "qcmm oswv rzlf ulkx"
  FROM_EMAIL: "noreply@sportify.com"