apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-service
  template:
    metadata:
      labels:
        app: team-service
    spec:
      containers:
        - name: team-service
          image: medhadji/team-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5004
          volumeMounts:
            - name: team-uploads
              mountPath: /usr/src/app/uploads
          envFrom:
            - secretRef:
                name: team-secrets
          env:
            - name: PORT
              value: "5004"
      volumes:
        - name: team-uploads
          persistentVolumeClaim:
            claimName: team-service-uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: team-service
spec:
  selector:
    app: team-service
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
  type: ClusterIP
