apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: team-service-uploads-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath