apiVersion: apps/v1
kind: Deployment
metadata:
  name: tournament-service
  namespace: default
  labels:
    app: tournament-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tournament-service
  template:
    metadata:
      labels:
        app: tournament-service
    spec:
      containers:
        - name: tournament-service
          image: medhadji/tournament-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4100
          envFrom:
            - secretRef:
                name: tournament-secrets
          env:
            - name: PORT
              value: "4100"
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:5000"
            - name: TEAM_SERVICE_URL
              value: "http://team-service:5004"
---
apiVersion: v1
kind: Service
metadata:
  name: tournament-service
  namespace: default
  labels:
    app: tournament-service
spec:
  selector:
    app: tournament-service
  ports:
    - protocol: TCP
      port: 4100
      targetPort: 4100
  type: ClusterIP
